import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CROWN Radio Club",
  description: "Generated by create next app",
  // icons: {
  //   icon: "/publicImage/crown_logo.jpg",       // Your custom image
  //   shortcut: "/publicImage/crown_logo.jpg",
  //   apple: "/publicImage/crown_logo.jpg",
  // },
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/publicImage/crown_logo.jpg" type="image/jpg" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
